import argparse


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument('repositories_path'
                        , type=str
                        , help='The path where project have been cloned\n')
    parser.add_argument('merge_csv_path'
                        , type=str
                        , help='The path of the file generated by merge-extractor script.\n')
    return parser.parse_args()